spring.thymeleaf.cache=true
security.basic.enabled=false
security.user.name=user
security.user.password=demo
management.security.enabled=${security.basic.enabled}
file.init.jsonfile-map={googlePage:"src\\test\\java\\jsonPage\\GooglePage.json"}
env.pdf.file = "C:\\Projects\\"
