spring.thymeleaf.cache=false
security.basic.enabled=false
security.user.name=user
security.user.password=demo
management.security.enabled=${security.basic.enabled}
file.init.jsonfile-map={homePage:"src\\test\\java\\jsonPage\\herokuapp\\HomePage.json", \
							listaDeFuncionalidade:"src\\test\\java\\jsonPage\\herokuapp\\ListaDeFuncionalidade.json", \
							formularioPage:"src\\test\\java\\jsonPage\\herokuapp\\FormularioPage.json"}
env.pdf.file = "C:\\Projects\\"

